In [1]:
from metacatalog import ext, api
from metacatalog_corr import metrics, extension, manage

import pandas as pd

In [2]:
# Local
CONNECTION = 'mc_corr'

session = api.connect_database(CONNECTION)
print(session.bind)

Engine(postgresql://postgres:***@localhost:5432/mc_corr)

In [3]:
entry_groups = []
entry_groups.extend(api.find_group(session, type=1, title='LTZ Augustenberg'))
entry_groups.extend(api.find_group(session, type=1, title='DWD station Rheinstetten'))
entry_groups.extend(api.find_group(session, type=1, title='Bühlot Dataset'))
entry_groups.extend(api.find_group(session, type=1, title='Sap Flow - Hohes Holz'))

# LUBW gauge network: Split datasets -> get result set to merge Split datasets
entry_groups.extend(api.find_group(session, type=1, title='LUBW gauge network', as_result=True))

entry_groups.extend(api.find_group(session, type=2, title='*Eddy*'))
entry_groups.extend(api.find_group(session, type=4))


for g in entry_groups:
    if str(type(g)) == "<class 'metacatalog.util.results.ImmutableResultSet'>":
        print(g.group.title)
    else:
        print(g.title)

LTZ Augustenberg
DWD station Rheinstetten
Bühlot Dataset
Sap Flow - Hohes Holz
LUBW gauge network
Fendt dataset: Eddy covariance data
Fendt 1 TERENO preAlpine Observatory / SUSALPS
Fendt 2 TERENO preAlpine Observatory / SUSALPS
Fendt 3 TERENO preAlpine Observatory / SUSALPS
Grasswang TERENO preAlpine Observatory / SUSALPS

# Test: what has been calculated, anything missing?

In [4]:
from metacatalog.util.results import ImmutableResultSet
from metacatalog.models import EntryGroup

group_n_entries = {}
for group in entry_groups:
    if type(group) == EntryGroup:
        group_n_entries[group.title] = len(group.entries)
    elif type(group) == ImmutableResultSet:
        group_n_entries[group.group.title] = len(group.group.entries)
        
n_entries = sum(group_n_entries.values())

metrics = ['pearson', 'spearman', 'dcor', 'mic', 'kendall_tau', 'weighted_tau', 
           'hoeffdings_d', 'perc_bend', 'biweight_mid', 'shepherd',
           'conditional_entropy', 'mutual_info', 'js_divergence', 'js_distance']

n_metrics = len(metrics)

# entries without datasource: no correlation matrix
sql = 'select * from entries where datasource_id is null'
no_datasource = pd.read_sql(sql, session.bind)
n_no_datasource = len(no_datasource)

n_entries = n_entries - n_no_datasource

for group in entry_groups:
    if type(group) == EntryGroup:
        n = n_entries #- group_n_entries[group.title]
        print(group_n_entries[group.title] * n)
    elif type(group) == ImmutableResultSet:
        group_n_entries[group.group.title] = len(group.group.entries)

6684
21166
46788
18938
7798
20052
20052
20052
20052

Wieso unterschiedlich viele Einträge in corr_matrix? Müsste nicht jede left_id gleich viele Einträge / Partner haben?

In [191]:
test = list(range(1, 1153, 1))

for number in test:
    if number not in set(df.left_id):
        print(number)

26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152

In [190]:
test = list(range(1, 1153, 1))

for number in test:
    if number not in set(df.right_id):
        print(number)

27
29
31
33
35
37
39
41
43
45
47
49
51
53
54
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
101
103
105
107
109
111
113
115
117
118
119
121
123
125
127
129
131
133
134
135
137
139
141
142
143
144
145
147
149
151
153
155
157
159
161
163
165
167
169
171
173
175
177
179
181
183
185
187
189
191
193
194
195
197
199
201
203
205
207
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
227
229
231
233
235
237
239
241
243
245
247
249
251
253
255
257
258
259
261
262
263
265
267
269
271
273
275
277
279
281
283
285
287
289
291
293
295
297
299
301
303
305
307
309
311
313
315
317
319
321
323
325
327
329
331
333
335
337
339
341
343
345
347
349
351
353
355
357
359
361
363
365
367
369
371
373
375
377
379
381
383
385
387
389
390
391
393
395
397
399
401
403
405
407
409
411
413
414
415
417
419
421
423
425
427
429
431
433
435
437
439
441
443
445
447
449
451
453
454
455
456
457
459
461
463
465
467
469
471
473
475
477
479
481
483
485
487
489
491
493
495
497
499
501
503
505
507
509
511
513
515
517
519
521
523
525
527
529
531
533
535
537
539
541
543
545
546
547
549
551
553
555
557
559
561
563
565
567
569
571
573
575
577
579
581
583
585
587
589
591
593
595
597
599
601
603
605
607
609
611
613
615
617
619
621
623
625
627
629
631
633
635
637
639
641
643
645
647
649
651
653
655
657
659
661
663
665
667
669
671
673
675
677
679
681
683
685
687
689
691
693
695
697
699
701
703
705
707
709
711
713
715
717
719
721
723
725
727
729
731
733
735
737
739
741
743
745
747
749
751
753
755
757
759
761
763
765
767
769
771
773
775
777
779
781
783
785
787
789
791
793
795
797
799
801
803
805
807
809
811
813
815
817
819
821
823
825
827
829
831
833
835
837
839
841
843
845
847
849
851
853
855
857
859
861
863
865
867
869
870
871
873
875
877
879
881
883
885
887
889
890
891
893
895
897
898
899
901
903
905
907
909
911
913
915
916
917
919
921
922
923
925
927
929
931
933
935
937
939
941
943
945
947
949
951
953
955
957
959
961
963
965
967
969
971
973
975
977
979
981
983
985
987
989
991
993
995
997
999
1001
1003
1005
1007
1009
1011
1013
1030
1031
1032

In [5]:
sql = 'select * from correlation_matrix order by left_id ASC, right_id'
df = pd.read_sql(sql, session.bind)
df.left_id.value_counts()

1       9534
5       9534
6       9534
2       9534
4       9534
        ...
1051      66
1052      66
1057      66
1056      66
1055      66
Name: left_id, Length: 83, dtype: int64

# All left <-> right combinations: len of all data_names in table data_sources

In [236]:
sql = 'select data_names from datasources'
datasource_data_names = pd.read_sql(sql, session.bind)

# unpack list of data_names (e.g. Eddy data, more than one column)
n_data_names = len(datasource_data_names.explode(column='data_names'))
print(n_data_names)

# only every second entry in LUBW is used (2 Entries are merged)
print(n_data_names - 494)

1167
673

In [234]:
(1167-494) * 6 * 14

56532

# Check conditional entropy

In [326]:
sql = 'select * from correlation_matrix where metric_id = 13' # conditional entropy
df = pd.read_sql(sql, session.bind)
id_fehlt = list(df.id[df.calculated < '2021-11-02'])

id_fehlt = list(map(str, id_fehlt))
id_fehlt = ', '.join(id_fehlt)

sql = 'select * from correlation_matrix where id in (%s)' % id_fehlt # conditional entropy
df = pd.read_sql(sql, session.bind)
df

ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near ")"
LINE 1: select * from correlation_matrix where id in ()
                                                      ^

[SQL: select * from correlation_matrix where id in ()]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [3]:
sql = 'select * from correlation_matrix order by calculated desc'
df = pd.read_sql(sql, session.bind)
df[0:15]

,id,metric_id,value,identifier,left_id,right_id,calculated
0,495115,14,-1.218071,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:13:07.172210
1,495114,13,-1.218071,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:13:04.648591
2,495113,11,-0.022932,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:13:02.986653
3,495112,10,-0.017460,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:13:00.555947
4,495111,9,NaN,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:12:59.972566
5,495110,8,0.000043,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:12:59.378695
6,495109,6,-0.137463,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:12:58.760181
7,495108,5,-0.049724,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:12:58.001646
8,495107,4,0.031488,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:12:57.432837
9,495106,3,0.003806,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:12:36.450628
10,495105,2,-0.061079,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:12:35.506030
11,495104,1,0.001500,"[precipitation, Cov(w'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:12:34.828260
12,495103,18,0.005481,"[precipitation, Cov(v'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:12:33.664420
13,495102,17,0.010933,"[precipitation, Cov(v'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:09:22.325884
14,495101,14,-9546.686524,"[precipitation, Cov(v'Ts')[(m*deg C)/s]], all ...",1014,1064,2021-11-15 18:01:49.548860

In [24]:
right = api.find_entry(session, id=1064, include_partial=True)[0]
right = right.get_data()

In [25]:
right_df['Cov(w\'Ts\')[(m*deg C)/s]']

tstamp
2014-01-01 00:30:00    0.001892
2014-01-01 01:00:00   -0.000621
2014-01-01 01:30:00    0.017899
2014-01-01 02:00:00    0.018810
2014-01-01 02:30:00   -0.003396
                         ...
2018-12-31 21:30:00   -0.022416
2018-12-31 22:00:00   -0.003006
2018-12-31 22:30:00   -0.003497
2018-12-31 23:00:00   -0.015182
2018-12-31 23:30:00    0.014144
Name: Cov(w'Ts')[(m*deg C)/s], Length: 87599, dtype: float64

In [ ]:
import numpy as np
import skinfo.metrics as skinfo

right_df = api.find_entry(session, id=1064, include_partial=True)[0]
right_df = right_df.get_data()

left_df = api.find_entry(session, id=1014)[0]
left_df = left_df.get_data()

right = right_df['Cov(v\'Ts\')[(m*deg C)/s]']
left = left_df

harmonized_index = right[right.index.isin(left.index)].index
left = left.loc[harmonized_index]
right = right.loc[harmonized_index]

left = left.to_numpy()
right = right.to_numpy()

#left = np.hstack(left)
#right = np.hstack(right)

nan_indices = np.logical_not(np.logical_or(np.isnan(left), np.isnan(right)))

left = left[nan_indices]
right = right[nan_indices]

corr = skinfo.mutual_information(left, right, 'fd')

print(corr)

In [ ]:
x=left
y=right
bins='fd'

# jensen shannon

# get the bins
bins = np.histogram_bin_edges([x, y], bins)

# calculate unconditioned histograms
hist_x = np.histogram(x, bins=bins)[0]
hist_y = np.histogram(y, bins=bins)[0]

# calculate probabilities
px = (hist_x / np.sum(hist_x)) + 1e-15
py = (hist_y / np.sum(hist_y)) + 1e-15

# calculate m
pm = 0.5 * (px + py)

# cross entropy 
#px = px + 1e-15
#py = pm + 1e-15
#
#cross_xm = - px.dot(np.log2(py))
#
#px = py + 1e-15
#py = pm + 1e-15
#
#cross_ym = - px.dot(np.log2(py))
#
## entropy x
#p = px + 1e-15
#entropy_x = - p.dot(np.log2(p))
#
#p = py + 1e-15
#entropy_y = - p.dot(np.log2(p))
#
#
#kl_xm = cross_xm - entropy_x
#kl_ym = cross_ym - entropy_x

In [7]:
pm

NameError: name 'pm' is not defined

In [14]:
import skinfo.metrics as skinfo

pm = 0.5 * (px + py)

# calculate kullback-leibler divergence between px and pm & py and pm
kl_xm = skinfo.kullback_leibler(px, pm, bins=bins, use_probs=True)
kl_ym = skinfo.kullback_leibler(py, pm, bins=bins, use_probs=True)

In [17]:
(0.5 * kl_xm + 0.5 * kl_ym)

0.9890672661383164

In [8]:
import skinfo.metrics as skinfo

skinfo.conditional_entropy(left,right,bins='fd')

-3.552713678800501e-15

In [ ]:
skinfo.conditional_entropy(left,right,bins='fd')

In [ ]:
extension.index_correlation_matrix(left, right_group._members, metrics=[17],
                                               harmonize=True, 
                                               identifier='all left+right, harmonize=True, merged Split dataset (l+r)',
                                               if_exists='replace', commit=False, verbose=True))

# Metric 13 -> da läuft wohl was schief!!
- skipped -> mal per Hand ausprobieren: left_id=1036, right_id=1074, metric=['conditional_entropy']
- skipped -> left_id=1074, right_id=1036, metric = ['conditional_entropy']

NICHT Skipped, skinfo functions (joint probabilities)

## Kernel Crash skinfo: left_id=1074, right_id=1036,metric=['conditional_entropy']
in beide Richtungen (left<->right)  
Kernel Crash beim Versuch joint histogram auszurechnen:
```python
left = api.find_entry(session, id=1036)[0]
left_dat = left.get_data()

right = api.find_entry(session, id=1074)[0]
right_dat = right.get_data()

left = left_dat
right = right_dat

harmonized_index = right[right.index.isin(left.index)].index
left = left.loc[harmonized_index]
right = right.loc[harmonized_index]

left = left.to_numpy()
right = right.to_numpy()

nan_indices = np.logical_not(np.logical_or(np.isnan(left), np.isnan(right)))
left = left[nan_indices]
right = right[nan_indices]

x=left
y=right
bins='fd'

bins_x = np.histogram_bin_edges(x, bins)
bins_y = np.histogram_bin_edges(y, bins) 
bins_xy = [bins_x, bins_y]

joint_hist = np.histogram2d(x, y, bins_xy)[0]
```
--> **KERNEL CRASH**

In [12]:
import numpy as np

In [7]:
#left = api.find_entry(session, id=1036)[0]
left = api.find_entry(session, id=1041)[0]
left_dat = left.get_data()
right = api.find_entry(session, id=1074)[0]
right_dat = right.get_data()

left = left_dat
right = right_dat

harmonized_index = right[right.index.isin(left.index)].index
left = left.loc[harmonized_index]
right = right.loc[harmonized_index]

left = left.to_numpy()
right = right.to_numpy()

nan_indices = np.logical_not(np.logical_or(np.isnan(left), np.isnan(right)))
left = left[nan_indices]
right = right[nan_indices]

x=left
y=right
bins='fd'

bins_x = np.histogram_bin_edges(x, bins)
bins_y = np.histogram_bin_edges(y, bins) 
bins_xy = [bins_x, bins_y]

# Kernel Crash:
#joint_hist = np.histogram2d(x, y, bins_xy)[0]
#joint_hist

In [6]:
entry_groups[0]

In [4]:
entry_kernel_crash_1 = api.find_entry(session, id=1036)[0]
entry_kernel_crash_2 = api.find_entry(session, id=1041)[0]

print(entry_groups[2].title)
#entry_groups[2].entries.remove(entry_kernel_crash_1)
#entry_groups[2].entries.remove(entry_kernel_crash_2)


for idx, entry in enumerate(entry_groups[2].entries):
    print(idx, entry.id, entry.title)

Bühlot Dataset
0 1014 Bühlot dataset: Rain Gauge Sternenberg, Precipitation_Sum
1 1015 Bühlot dataset: Rain Gauge Sternenberg, Temperature_Air
2 1016 Bühlot dataset: Rain Gauge Wintereck, Precipitation_Sum
3 1017 Bühlot dataset: Rain Gauge Wintereck, Temperature_Air
4 1018 Bühlot dataset: Rain Gauge Sportplatz Obertal, Precipitation_Sum
5 1019 Bühlot dataset: Rain Gauge Sportplatz Obertal, Temperature_Air
6 1020 Bühlot dataset: Rain Gauge Schoenbrunn, Precipitation_Sum
7 1021 Bühlot dataset: Rain Gauge Schoenbrunn, Temperature_Air
8 1022 Bühlot dataset: Rain Gauge Schwabenquelle, Precipitation_Sum
9 1023 Bühlot dataset: Rain Gauge Schwabenquelle, Temperature_Air
10 1024 Bühlot dataset: Level Schwabenquelle, Water_Level
11 1025 Bühlot dataset: Level Schwabenquelle, Temperature_Water
12 1026 Bühlot dataset: Rain Gauge Hundseck, Precipitation_Sum
13 1027 Bühlot dataset: Rain Gauge Hundseck, Temperature_Air
14 1028 Bühlot dataset: Rain Gauge Grundigklinik, Precipitation_Sum
15 1029 Bühlot dataset: Rain Gauge Grundigklinik, Temperature_Air
16 1030 Bühlot dataset: Tensiometer Sprengquellen Down North, Water_Level
17 1031 Bühlot dataset: Tensiometer Sprengquellen Down North, Temperature_Water
18 1032 Bühlot dataset: Tensiometer Sprengquellen Down North, Temperature_Air
19 1033 Bühlot dataset: Tensiometer Sprengquellen Top North, Water_Level
20 1034 Bühlot dataset: Tensiometer Sprengquellen Top North, Temperature_Water
21 1035 Bühlot dataset: Tensiometer Sprengquellen Top North, Temperature_Air
22 1037 Bühlot dataset: Tensiometer Sprengquellen Top South, Temperature_Air
23 1038 Bühlot dataset: Tensiometer Sprengquellen Top South, Temperature_Water
24 1039 Bühlot dataset: Rain Gauge Schafhof, Precipitation_Sum
25 1040 Bühlot dataset: Rain Gauge Schafhof, Temperature_Air
26 1041 Bühlot dataset: Tensiometer Schafhof, Water_Level
27 1042 Bühlot dataset: Tensiometer Schafhof, Temperature_Water
28 1043 Bühlot dataset: Tensiometer Schafhof, Temperature_Air
29 1044 Bühlot dataset: Soil Moisture Schafhof No5, Volumetric_Soil_Moisture_20cm
30 1045 Bühlot dataset: Soil Moisture Schafhof No5, Electrical_Coductivity_20cm
31 1046 Bühlot dataset: Soil Moisture Schafhof No5, Soil_Temperature_20cm
32 1047 Bühlot dataset: Soil Moisture Schafhof No5, Volumetric_Soil_Moisture_50cm
33 1048 Bühlot dataset: Soil Moisture Schafhof No5, Electrical_Coductivity_50cm
34 1049 Bühlot dataset: Soil Moisture Schafhof No5, Soil_Temperature_50cm
35 1050 Bühlot dataset: Soil Moisture Schafhof No1, Volumetric_Soil_Moisture_20cm
36 1051 Bühlot dataset: Soil Moisture Schafhof No1, Electrical_Coductivity_20cm
37 1052 Bühlot dataset: Soil Moisture Schafhof No1, Soil_Temperature_20cm
38 1053 Bühlot dataset: Soil Moisture Schafhof No1, Volumetric_Soil_Moisture_50cm
39 1054 Bühlot dataset: Soil Moisture Schafhof No1, Electrical_Coductivity_50cm
40 1055 Bühlot dataset: Soil Moisture Schafhof No1, Soil_Temperature_50cm
41 1056 Bühlot dataset: Rain Gauge Butschenberg, Precipitation_Sum
42 1057 Bühlot dataset: Rain Gauge Butschenberg, Temperature_Air

In [15]:
entry_kernel_crash_2.associated_groups

In [21]:
entry_groups[2].entries.remove(entry_kernel_crash)

In [11]:
entry_kernel_crash.associated_groups[0].entries

[<metacatalog.models.entry.Entry at 0x7feebb9f17c0>,
 <metacatalog.models.entry.Entry at 0x7feebbb9a160>,
 <metacatalog.models.entry.Entry at 0x7feebbbaeee0>,
 <metacatalog.models.entry.Entry at 0x7feebbc3bfa0>,
 <metacatalog.models.entry.Entry at 0x7feebbc4a6a0>,
 <metacatalog.models.entry.Entry at 0x7feebbc73400>,
 <metacatalog.models.entry.Entry at 0x7feeceac8df0>,
 <metacatalog.models.entry.Entry at 0x7feecea93a30>,
 <metacatalog.models.entry.Entry at 0x7feebbcb7670>,
 <metacatalog.models.entry.Entry at 0x7feeceaaa610>,
 <metacatalog.models.entry.Entry at 0x7feeceabdd30>,
 <metacatalog.models.entry.Entry at 0x7feebbccacd0>,
 <metacatalog.models.entry.Entry at 0x7feebbccae20>,
 <metacatalog.models.entry.Entry at 0x7feebbce25e0>,
 <metacatalog.models.entry.Entry at 0x7feebbcf5a30>,
 <metacatalog.models.entry.Entry at 0x7feebbd2a130>,
 <metacatalog.models.entry.Entry at 0x7feebbd0c3a0>,
 <metacatalog.models.entry.Entry at 0x7feebbd0c730>,
 <metacatalog.models.entry.Entry at 0x7feebbd20d60>,
 <metacatalog.models.entry.Entry at 0x7feebbd5c760>,
 <metacatalog.models.entry.Entry at 0x7feebbd73070>,
 <metacatalog.models.entry.Entry at 0x7feebbd39880>,
 <metacatalog.models.entry.Entry at 0x7feeb9952f40>,
 <metacatalog.models.entry.Entry at 0x7feebbd39a30>,
 <metacatalog.models.entry.Entry at 0x7feebbd397f0>,
 <metacatalog.models.entry.Entry at 0x7feebbd52610>,
 <metacatalog.models.entry.Entry at 0x7feebbd524f0>,
 <metacatalog.models.entry.Entry at 0x7feebbd2f2e0>,
 <metacatalog.models.entry.Entry at 0x7feebbd64c40>,
 <metacatalog.models.entry.Entry at 0x7feebbd64af0>,
 <metacatalog.models.entry.Entry at 0x7feebbd64940>,
 <metacatalog.models.entry.Entry at 0x7feebbd7b1c0>,
 <metacatalog.models.entry.Entry at 0x7feebbd7b4c0>,
 <metacatalog.models.entry.Entry at 0x7feebbd7b4f0>,
 <metacatalog.models.entry.Entry at 0x7feebbd7b5e0>,
 <metacatalog.models.entry.Entry at 0x7feebbd7b6d0>,
 <metacatalog.models.entry.Entry at 0x7feebbd7b7c0>,
 <metacatalog.models.entry.Entry at 0x7feebbd7b8b0>,
 <metacatalog.models.entry.Entry at 0x7feebbd7b9a0>,
 <metacatalog.models.entry.Entry at 0x7feebbd7ba90>,
 <metacatalog.models.entry.Entry at 0x7feebbd7bb80>,
 <metacatalog.models.entry.Entry at 0x7feebbd7bc70>,
 <metacatalog.models.entry.Entry at 0x7feebbd7bd60>,
 <metacatalog.models.entry.Entry at 0x7feebbd7be50>]

In [13]:
left.id

1036